name: Deploy Staging to GitHub Pages

on:
    push:
        branches: [stg]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📦 Checkout Repository
              uses: actions/checkout@v3

            - name: 🔧 Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Install Dependencies
              run: npm ci

            - name: 🚧 Build and Export
              env:
                  STAGE: github
              run: |
                  npm run build
                  npm run export

            - name: 🚀 Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
                  publish_branch: gh-pages
